[2024-12-25T00:00:01.916+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T00:00:01.919+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available scheduled__2024-12-24T00:00:00+00:00 [queued]>
[2024-12-25T00:00:01.919+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T00:00:01.919+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-12-25T00:00:01.919+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T00:00:01.924+0000] {taskinstance.py:1300} INFO - Executing <Task(HttpSensor): is_api_available> on 2024-12-24 00:00:00+00:00
[2024-12-25T00:00:01.926+0000] {standard_task_runner.py:55} INFO - Started process 15487 to run task
[2024-12-25T00:00:01.928+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'scheduled__2024-12-24T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpck0u2p32']
[2024-12-25T00:00:01.928+0000] {standard_task_runner.py:83} INFO - Job 207: Subtask is_api_available
[2024-12-25T00:00:01.951+0000] {task_command.py:388} INFO - Running <TaskInstance: user_processing.is_api_available scheduled__2024-12-24T00:00:00+00:00 [running]> on host 44e036a430cc
[2024-12-25T00:00:01.975+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2024-12-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-24T00:00:00+00:00
[2024-12-25T00:00:01.976+0000] {http.py:122} INFO - Poking: api/
[2024-12-25T00:00:01.979+0000] {base.py:73} INFO - Using connection ID 'user_api' for task execution.
[2024-12-25T00:00:02.063+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/urllib3/connectionpool.py:1052: InsecureRequestWarning: Unverified HTTPS request is being made to host 'randomuser.me'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,

[2024-12-25T00:00:02.629+0000] {base.py:228} INFO - Success criteria met. Exiting.
[2024-12-25T00:00:02.642+0000] {taskinstance.py:1323} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20241224T000000, start_date=20241225T000001, end_date=20241225T000002
[2024-12-25T00:00:02.664+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2024-12-25T00:00:02.687+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
